import Centre from '@components/HawkerCentre/Centre';
import Footer from '@components/shared/Footer';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';

const Home: NextPage = () => {
	const router = useRouter();
	const { id } = router.query;
	return (
		<div>
			<Head>
				<title>HawkerHawk - Find hawker centres in Singapore</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Centre id={Number(id)} />
			<Footer />
		</div>
	);
};

export default Home;
