import HawkerCentres from '@components/HawkerCentres/HawkerCentres';
import type { NextPage } from 'next';
import Head from 'next/head';
import ScrollToTop from '@components/shared/ScrollToTop';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>HawkerHawk - Find hawker centres in Singapore</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<HawkerCentres />
			<ScrollToTop />
		</div>
	);
};

export default Home;
